select * from "Sales" limit 20

--Q1. What is the total sales and profit generated by each region?
select "Region" , sum("Sales")  as "Total_sales",
                  sum("Profit")  as "Total_profit" from "Sales"
group by "Region"
order by "Total_sales" desc;

--Q2. Which cities contribute the highest revenue?
select "City" , sum("Sales") as "Revenue" from "Sales"
group by "City"
order by "Revenue" desc;

--Q3. Which product categories generate the most profit?
select "Category" , sum("Profit") as "Most profit" from "Sales"
group by "Category"
order by "Most profit" desc;

--Q4. What are the top 10 products by total sales?
select "Product Name" , sum("Sales") as "Total_sales" from "Sales"
group by "Product Name"
order by "Total_sales" desc limit 10;

--Q5. Which products generate the highest profit margin?
select
    "Product Name", sum("Sales")  as "Total_Sales",
    sum("Profit") as "Total_Profit",
    sum("Profit") * 100.0 / sum("Sales")  as "Profit_Margin_%"
from "Sales"
group by "Product Name"
order by "Profit_Margin_%" desc
limit 10;

--Q6. Which products are sold in the highest quantities?
select "Product Name" , sum("Quantity") as "Highest Quantity" from "Sales"
group by "Product Name"
order by "Highest Quantity" desc limit 10;

--Q7. What is the average discount offered by each category?
select
    "Category", ROUND(avg("Discount"), 2) as "Average_Discount"
from "Sales"
group by "Category"
order by "Average_Discount" desc;

--Q8. Which payment mode is used most frequently?
select "Payment Mode" , count("Sales") as "Most_payment" from "Sales"
group by "Payment Mode"
order by "Most_payment" desc;

--Q9. Compare sales and profit across different payment modes.
select "Payment Mode" , sum("Sales")  as "Total Sales", sum("Profit") as "Total_profit"
from "Sales"
group by "Payment Mode";



